# Generated by Django 5.0.2 on 2024-03-09 05:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='time_in',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 9, 11, 47, 55, 274526)),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='time_out',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 9, 11, 47, 55, 274526)),
        ),
    ]
